---
- name: RancherServer
  hosts: rancherserver
  sudo: True
  tasks:
  - name: update_cache
    apt: update_cache=yes cache_valid_time=3600
  - name: Install python
    apt: name=python state=present
  - name: Install python-pip
    apt: name=python-pip state=present
  - name: Install docker-py
    pip: name=docker-py version=1.1.0
  - name: openVPNdata container
    docker:
      name: ovpn-data
      image: busybox
      state: reloaded
      restart_policy: always
      volumes:
      - "/etc/openvpn"
  - name: openVPN container
    docker:
      name: openvpn
      image: kylemanna/openvpn
      state: reloaded
      restart_policy: always
      volumes_from:
        - ovpn-data
      ports:
      - "8080:8080"
