---
- name: OpenVPN config
  hosts: openvpn
  vars:
     url_contents: "{{ lookup('file', 'url') }}"
  sudo: True
  tasks:
  - name: openVPN config
    docker:
      image: kylemanna/openvpn
      state: restarted
      volumes_from:
        - ovpn-data
      command: ovpn_genconfig -u "{{ url_contents }}"
